"""create plants table

Revision ID: aede3159afb1
Revises: 76def31c8f5a
Create Date: 2025-09-16 10:17:43.927498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aede3159afb1'
down_revision = '76def31c8f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
