"""Add defaults to Plant

Revision ID: f18895908931
Revises: aede3159afb1
Create Date: 2025-09-16 10:25:04.729664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18895908931'
down_revision = 'aede3159afb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
